<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Data Manipulation – Introduction to Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-exploration.html" rel="next">
<link href="./05-visualization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-manipulation.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Manipulation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reproducible Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Python Refreshment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-manipulation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Manipulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-exploration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data Exploration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-supervised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Supervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-unsupervised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Unsupervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./90-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Advanced Topics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">6.1</span> Introduction</a></li>
  <li><a href="#example-nyc-crash-data" id="toc-example-nyc-crash-data" class="nav-link" data-scroll-target="#example-nyc-crash-data"><span class="header-section-number">6.2</span> Example: NYC Crash Data</a></li>
  <li><a href="#accessing-census-data" id="toc-accessing-census-data" class="nav-link" data-scroll-target="#accessing-census-data"><span class="header-section-number">6.3</span> Accessing Census Data</a>
  <ul class="collapse">
  <li><a href="#python-tools-for-accessing-census-data" id="toc-python-tools-for-accessing-census-data" class="nav-link" data-scroll-target="#python-tools-for-accessing-census-data"><span class="header-section-number">6.3.1</span> Python Tools for Accessing Census Data</a></li>
  <li><a href="#zip-code-level-for-nyc-crash-data" id="toc-zip-code-level-for-nyc-crash-data" class="nav-link" data-scroll-target="#zip-code-level-for-nyc-crash-data"><span class="header-section-number">6.3.2</span> Zip-Code Level for NYC Crash Data</a></li>
  </ul></li>
  <li><a href="#cross-platform-data-format-arrow" id="toc-cross-platform-data-format-arrow" class="nav-link" data-scroll-target="#cross-platform-data-format-arrow"><span class="header-section-number">6.4</span> Cross-platform Data Format <code>Arrow</code></a></li>
  <li><a href="#database-operation-with-sql" id="toc-database-operation-with-sql" class="nav-link" data-scroll-target="#database-operation-with-sql"><span class="header-section-number">6.5</span> Database operation with SQL</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="header-section-number">6.5.1</span> Introduction</a></li>
  <li><a href="#setting-up-databases" id="toc-setting-up-databases" class="nav-link" data-scroll-target="#setting-up-databases"><span class="header-section-number">6.5.2</span> Setting up Databases</a></li>
  <li><a href="#query-basics" id="toc-query-basics" class="nav-link" data-scroll-target="#query-basics"><span class="header-section-number">6.5.3</span> Query Basics</a></li>
  <li><a href="#conditionals" id="toc-conditionals" class="nav-link" data-scroll-target="#conditionals"><span class="header-section-number">6.5.4</span> Conditionals</a></li>
  <li><a href="#joins" id="toc-joins" class="nav-link" data-scroll-target="#joins"><span class="header-section-number">6.5.5</span> Joins</a></li>
  <li><a href="#creating-tables" id="toc-creating-tables" class="nav-link" data-scroll-target="#creating-tables"><span class="header-section-number">6.5.6</span> Creating Tables</a></li>
  <li><a href="#statement-order" id="toc-statement-order" class="nav-link" data-scroll-target="#statement-order"><span class="header-section-number">6.5.7</span> Statement Order</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6.5.8</span> Conclusion</a></li>
  <li><a href="#further-readings" id="toc-further-readings" class="nav-link" data-scroll-target="#further-readings"><span class="header-section-number">6.5.9</span> Further Readings</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Manipulation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">6.1</span> Introduction</h2>
<p>Data manipulation is crucial for transforming raw data into a more analyzable format, essential for uncovering patterns and ensuring accurate analysis. This chapter introduces the core techniques for data manipulation in Python, utilizing the Pandas library, a cornerstone for data handling within Python’s data science toolkit.</p>
<p>Python’s ecosystem is rich with libraries that facilitate not just data manipulation but comprehensive data analysis. Pandas, in particular, provides extensive functionality for data manipulation tasks including reading, cleaning, transforming, and summarizing data. Using real-world datasets, we will explore how to leverage Python for practical data manipulation tasks.</p>
<p>By the end of this chapter, you will learn to:</p>
<ul>
<li>Import/export data from/to diverse sources.</li>
<li>Clean and preprocess data efficiently.</li>
<li>Transform and aggregate data to derive insights.</li>
<li>Merge and concatenate datasets from various origins.</li>
<li>Analyze real-world datasets using these techniques.</li>
</ul>
<!-- This section is to be included as a tutorial on pandas. -->
<!-- {{< include _pandas.qmd >}} -->
</section>
<section id="example-nyc-crash-data" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="example-nyc-crash-data"><span class="header-section-number">6.2</span> Example: NYC Crash Data</h2>
<p>Consider a subset of the NYC Crash Data, which contains all NYC motor vehicle collisions data with documentation from <a href="https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95">NYC Open Data</a>. We downloaded the crash data for the week of August 31, 2025, on September 11, 2025, in CSC format.</p>
<div id="dcca7217" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'data/nyc_crashes_lbdwk_2025.csv'</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(file_path,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                 dtype<span class="op">=</span>{<span class="st">'LATITUDE'</span>: np.float32,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">'LONGITUDE'</span>: np.float32,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                        <span class="st">'ZIP CODE'</span>: <span class="bu">str</span>})</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace column names: convert to lowercase and replace spaces with underscores</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>df.columns <span class="op">=</span> df.columns.<span class="bu">str</span>.lower().<span class="bu">str</span>.replace(<span class="st">' '</span>, <span class="st">'_'</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>crash_date                          0
crash_time                          0
borough                           284
zip_code                          284
latitude                           12
longitude                          12
location                           12
on_street_name                    456
cross_street_name                 587
off_street_name                  1031
number_of_persons_injured           0
number_of_persons_killed            0
number_of_pedestrians_injured       0
number_of_pedestrians_killed        0
number_of_cyclist_injured           0
number_of_cyclist_killed            0
number_of_motorist_injured          0
number_of_motorist_killed           0
contributing_factor_vehicle_1       9
contributing_factor_vehicle_2     355
contributing_factor_vehicle_3    1358
contributing_factor_vehicle_4    1447
contributing_factor_vehicle_5    1474
collision_id                        0
vehicle_type_code_1                17
vehicle_type_code_2               475
vehicle_type_code_3              1363
vehicle_type_code_4              1452
vehicle_type_code_5              1474
dtype: int64</code></pre>
</div>
</div>
<p>Take a peek at the first five rows:</p>
<div id="7fb464ab" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">crash_date</th>
<th data-quarto-table-cell-role="th">crash_time</th>
<th data-quarto-table-cell-role="th">borough</th>
<th data-quarto-table-cell-role="th">zip_code</th>
<th data-quarto-table-cell-role="th">latitude</th>
<th data-quarto-table-cell-role="th">longitude</th>
<th data-quarto-table-cell-role="th">location</th>
<th data-quarto-table-cell-role="th">on_street_name</th>
<th data-quarto-table-cell-role="th">cross_street_name</th>
<th data-quarto-table-cell-role="th">off_street_name</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">contributing_factor_vehicle_2</th>
<th data-quarto-table-cell-role="th">contributing_factor_vehicle_3</th>
<th data-quarto-table-cell-role="th">contributing_factor_vehicle_4</th>
<th data-quarto-table-cell-role="th">contributing_factor_vehicle_5</th>
<th data-quarto-table-cell-role="th">collision_id</th>
<th data-quarto-table-cell-role="th">vehicle_type_code_1</th>
<th data-quarto-table-cell-role="th">vehicle_type_code_2</th>
<th data-quarto-table-cell-role="th">vehicle_type_code_3</th>
<th data-quarto-table-cell-role="th">vehicle_type_code_4</th>
<th data-quarto-table-cell-role="th">vehicle_type_code_5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>08/31/2025</td>
<td>12:49</td>
<td>QUEENS</td>
<td>11101</td>
<td>40.753113</td>
<td>-73.933701</td>
<td>(40.753113, -73.9337)</td>
<td>30 ST</td>
<td>39 AVE</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>4838875</td>
<td>Station Wagon/Sport Utility Vehicle</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>08/31/2025</td>
<td>15:30</td>
<td>MANHATTAN</td>
<td>10022</td>
<td>40.760601</td>
<td>-73.964317</td>
<td>(40.7606, -73.96432)</td>
<td>E 59 ST</td>
<td>2 AVE</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>4839110</td>
<td>Station Wagon/Sport Utility Vehicle</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>08/31/2025</td>
<td>19:00</td>
<td>NaN</td>
<td>NaN</td>
<td>40.734234</td>
<td>-73.722748</td>
<td>(40.734234, -73.72275)</td>
<td>CROSS ISLAND PARKWAY</td>
<td>HILLSIDE AVENUE</td>
<td>NaN</td>
<td>...</td>
<td>Unspecified</td>
<td>Unspecified</td>
<td>NaN</td>
<td>NaN</td>
<td>4838966</td>
<td>Sedan</td>
<td>Sedan</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>08/31/2025</td>
<td>1:19</td>
<td>BROOKLYN</td>
<td>11220</td>
<td>40.648075</td>
<td>-74.007034</td>
<td>(40.648075, -74.007034)</td>
<td>NaN</td>
<td>NaN</td>
<td>4415 5 AVE</td>
<td>...</td>
<td>Unspecified</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>4838563</td>
<td>Sedan</td>
<td>E-Bike</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>08/31/2025</td>
<td>2:41</td>
<td>MANHATTAN</td>
<td>10036</td>
<td>40.756561</td>
<td>-73.986107</td>
<td>(40.75656, -73.98611)</td>
<td>W 43 ST</td>
<td>BROADWAY</td>
<td>NaN</td>
<td>...</td>
<td>Unspecified</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>4838922</td>
<td>Station Wagon/Sport Utility Vehicle</td>
<td>Bike</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>5 rows × 29 columns</p>
</div>
</div>
</div>
<p>A quick summary of the data types of the columns:</p>
<div id="166327f6" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 1487 entries, 0 to 1486
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   crash_date                     1487 non-null   object 
 1   crash_time                     1487 non-null   object 
 2   borough                        1203 non-null   object 
 3   zip_code                       1203 non-null   object 
 4   latitude                       1475 non-null   float32
 5   longitude                      1475 non-null   float32
 6   location                       1475 non-null   object 
 7   on_street_name                 1031 non-null   object 
 8   cross_street_name              900 non-null    object 
 9   off_street_name                456 non-null    object 
 10  number_of_persons_injured      1487 non-null   int64  
 11  number_of_persons_killed       1487 non-null   int64  
 12  number_of_pedestrians_injured  1487 non-null   int64  
 13  number_of_pedestrians_killed   1487 non-null   int64  
 14  number_of_cyclist_injured      1487 non-null   int64  
 15  number_of_cyclist_killed       1487 non-null   int64  
 16  number_of_motorist_injured     1487 non-null   int64  
 17  number_of_motorist_killed      1487 non-null   int64  
 18  contributing_factor_vehicle_1  1478 non-null   object 
 19  contributing_factor_vehicle_2  1132 non-null   object 
 20  contributing_factor_vehicle_3  129 non-null    object 
 21  contributing_factor_vehicle_4  40 non-null     object 
 22  contributing_factor_vehicle_5  13 non-null     object 
 23  collision_id                   1487 non-null   int64  
 24  vehicle_type_code_1            1470 non-null   object 
 25  vehicle_type_code_2            1012 non-null   object 
 26  vehicle_type_code_3            124 non-null    object 
 27  vehicle_type_code_4            35 non-null     object 
 28  vehicle_type_code_5            13 non-null     object 
dtypes: float32(2), int64(9), object(18)
memory usage: 325.4+ KB</code></pre>
</div>
</div>
<p>Now we can do some cleaning after a quick browse.</p>
<div id="232ab807" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace invalid coordinates (latitude=0, longitude=0 or NaN) with NaN</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df.loc[(df[<span class="st">'latitude'</span>] <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (df[<span class="st">'longitude'</span>] <span class="op">==</span> <span class="dv">0</span>), </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>       [<span class="st">'latitude'</span>, <span class="st">'longitude'</span>]] <span class="op">=</span> pd.NA</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'latitude'</span>] <span class="op">=</span> df[<span class="st">'latitude'</span>].replace(<span class="dv">0</span>, pd.NA)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'longitude'</span>] <span class="op">=</span> df[<span class="st">'longitude'</span>].replace(<span class="dv">0</span>, pd.NA)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the redundant `latitute` and `longitude` columns</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(columns<span class="op">=</span>[<span class="st">'location'</span>])</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting 'crash_date' and 'crash_time' columns into a single datetime column</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'crash_datetime'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'crash_date'</span>] <span class="op">+</span> <span class="st">' '</span> </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                       <span class="op">+</span> df[<span class="st">'crash_time'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%m/</span><span class="sc">%d</span><span class="st">/%Y %H:%M'</span>, errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the original 'crash_date' and 'crash_time' columns</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(columns<span class="op">=</span>[<span class="st">'crash_date'</span>, <span class="st">'crash_time'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s get some basic frequency tables of <code>borough</code> and <code>zip_code</code>, whose values could be used to check their validity against the legitmate values.</p>
<div id="a4d21bb9" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequency table for 'borough' without filling missing values</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>borough_freq <span class="op">=</span> df[<span class="st">'borough'</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>).reset_index()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>borough_freq.columns <span class="op">=</span> [<span class="st">'borough'</span>, <span class="st">'count'</span>]</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequency table for 'zip_code' without filling missing values</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>zip_code_freq <span class="op">=</span> df[<span class="st">'zip_code'</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>).reset_index()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>zip_code_freq.columns <span class="op">=</span> [<span class="st">'zip_code'</span>, <span class="st">'count'</span>]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>zip_code_freq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">zip_code</th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>NaN</td>
<td>284</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>11207</td>
<td>33</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>11203</td>
<td>29</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>11212</td>
<td>23</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>11233</td>
<td>21</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">159</td>
<td>11379</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">160</td>
<td>10007</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">161</td>
<td>10308</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">162</td>
<td>11362</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">163</td>
<td>11694</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>164 rows × 2 columns</p>
</div>
</div>
</div>
<p>A comprehensive list of ZIP codes by borough can be obtained, for example, from <a href="https://www.nyc.gov/assets/doh/downloads/pdf/ah/zipcodetable.pdf">the New York City Department of Health’s UHF Codes</a>. We can use this list to check the validity of the zip codes in the data.</p>
<div id="6e4fee3e" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of valid NYC ZIP codes compiled from UHF codes</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define all_valid_zips based on the earlier extracted ZIP codes</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>all_valid_zips <span class="op">=</span> {</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10463</span>, <span class="dv">10471</span>, <span class="dv">10466</span>, <span class="dv">10469</span>, <span class="dv">10470</span>, <span class="dv">10475</span>, <span class="dv">10458</span>, <span class="dv">10467</span>, <span class="dv">10468</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10461</span>, <span class="dv">10462</span>, <span class="dv">10464</span>, <span class="dv">10465</span>, <span class="dv">10472</span>, <span class="dv">10473</span>, <span class="dv">10453</span>, <span class="dv">10457</span>, <span class="dv">10460</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10451</span>, <span class="dv">10452</span>, <span class="dv">10456</span>, <span class="dv">10454</span>, <span class="dv">10455</span>, <span class="dv">10459</span>, <span class="dv">10474</span>, <span class="dv">11211</span>, <span class="dv">11222</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11201</span>, <span class="dv">11205</span>, <span class="dv">11215</span>, <span class="dv">11217</span>, <span class="dv">11231</span>, <span class="dv">11213</span>, <span class="dv">11212</span>, <span class="dv">11216</span>, <span class="dv">11233</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11238</span>, <span class="dv">11207</span>, <span class="dv">11208</span>, <span class="dv">11220</span>, <span class="dv">11232</span>, <span class="dv">11204</span>, <span class="dv">11218</span>, <span class="dv">11219</span>, <span class="dv">11230</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11203</span>, <span class="dv">11210</span>, <span class="dv">11225</span>, <span class="dv">11226</span>, <span class="dv">11234</span>, <span class="dv">11236</span>, <span class="dv">11239</span>, <span class="dv">11209</span>, <span class="dv">11214</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11228</span>, <span class="dv">11223</span>, <span class="dv">11224</span>, <span class="dv">11229</span>, <span class="dv">11235</span>, <span class="dv">11206</span>, <span class="dv">11221</span>, <span class="dv">11237</span>, <span class="dv">10031</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10032</span>, <span class="dv">10033</span>, <span class="dv">10034</span>, <span class="dv">10040</span>, <span class="dv">10026</span>, <span class="dv">10027</span>, <span class="dv">10030</span>, <span class="dv">10037</span>, <span class="dv">10039</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10029</span>, <span class="dv">10035</span>, <span class="dv">10023</span>, <span class="dv">10024</span>, <span class="dv">10025</span>, <span class="dv">10021</span>, <span class="dv">10028</span>, <span class="dv">10044</span>, <span class="dv">10128</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10001</span>, <span class="dv">10011</span>, <span class="dv">10018</span>, <span class="dv">10019</span>, <span class="dv">10020</span>, <span class="dv">10036</span>, <span class="dv">10010</span>, <span class="dv">10016</span>, <span class="dv">10017</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10022</span>, <span class="dv">10012</span>, <span class="dv">10013</span>, <span class="dv">10014</span>, <span class="dv">10002</span>, <span class="dv">10003</span>, <span class="dv">10009</span>, <span class="dv">10004</span>, <span class="dv">10005</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10006</span>, <span class="dv">10007</span>, <span class="dv">10038</span>, <span class="dv">10280</span>, <span class="dv">11101</span>, <span class="dv">11102</span>, <span class="dv">11103</span>, <span class="dv">11104</span>, <span class="dv">11105</span>,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11106</span>, <span class="dv">11368</span>, <span class="dv">11369</span>, <span class="dv">11370</span>, <span class="dv">11372</span>, <span class="dv">11373</span>, <span class="dv">11377</span>, <span class="dv">11378</span>, <span class="dv">11354</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11355</span>, <span class="dv">11356</span>, <span class="dv">11357</span>, <span class="dv">11358</span>, <span class="dv">11359</span>, <span class="dv">11360</span>, <span class="dv">11361</span>, <span class="dv">11362</span>, <span class="dv">11363</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11364</span>, <span class="dv">11374</span>, <span class="dv">11375</span>, <span class="dv">11379</span>, <span class="dv">11385</span>, <span class="dv">11365</span>, <span class="dv">11366</span>, <span class="dv">11367</span>, <span class="dv">11414</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11415</span>, <span class="dv">11416</span>, <span class="dv">11417</span>, <span class="dv">11418</span>, <span class="dv">11419</span>, <span class="dv">11420</span>, <span class="dv">11421</span>, <span class="dv">11412</span>, <span class="dv">11423</span>,</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11432</span>, <span class="dv">11433</span>, <span class="dv">11434</span>, <span class="dv">11435</span>, <span class="dv">11436</span>, <span class="dv">11004</span>, <span class="dv">11005</span>, <span class="dv">11411</span>, <span class="dv">11413</span>,</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11422</span>, <span class="dv">11426</span>, <span class="dv">11427</span>, <span class="dv">11428</span>, <span class="dv">11429</span>, <span class="dv">11691</span>, <span class="dv">11692</span>, <span class="dv">11693</span>, <span class="dv">11694</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    <span class="dv">11695</span>, <span class="dv">11697</span>, <span class="dv">10302</span>, <span class="dv">10303</span>, <span class="dv">10310</span>, <span class="dv">10301</span>, <span class="dv">10304</span>, <span class="dv">10305</span>, <span class="dv">10314</span>,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10306</span>, <span class="dv">10307</span>, <span class="dv">10308</span>, <span class="dv">10309</span>, <span class="dv">10312</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert set to list of strings</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>all_valid_zips <span class="op">=</span> <span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">str</span>, all_valid_zips))</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify invalid ZIP codes (including NaN)</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>invalid_zips <span class="op">=</span> df[</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'zip_code'</span>].isna() <span class="op">|</span> <span class="op">~</span>df[<span class="st">'zip_code'</span>].isin(all_valid_zips)</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    ][<span class="st">'zip_code'</span>]</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate frequency of invalid ZIP codes</span></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>invalid_zip_freq <span class="op">=</span> invalid_zips.value_counts(dropna<span class="op">=</span><span class="va">False</span>).reset_index()</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>invalid_zip_freq.columns <span class="op">=</span> [<span class="st">'zip_code'</span>, <span class="st">'frequency'</span>]</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>invalid_zip_freq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">zip_code</th>
<th data-quarto-table-cell-role="th">frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>NaN</td>
<td>284</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>10000</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>10065</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>10075</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>11430</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>As it turns out, the collection of valid NYC zip codes differ from different sources. From <a href="https://www.unitedstateszipcodes.org/">United States Zip Codes</a>, <code>10065</code> appears to be a valid NYC zip code. Under this circumstance, it might be safer to not remove any zip code from the data.</p>
<p>To be safe, let’s concatenate valid and invalid zips.</p>
<div id="48e6c669" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert invalid ZIP codes to a set of strings</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>invalid_zips_set <span class="op">=</span> <span class="bu">set</span>(invalid_zip_freq[<span class="st">'zip_code'</span>].dropna().astype(<span class="bu">str</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all_valid_zips to a set of strings (if not already)</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>valid_zips_set <span class="op">=</span> <span class="bu">set</span>(<span class="bu">map</span>(<span class="bu">str</span>, all_valid_zips))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge both sets</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>merged_zips <span class="op">=</span> invalid_zips_set <span class="op">|</span> valid_zips_set  <span class="co"># Union of both sets</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Are missing in zip code and borough always co-occur?</p>
<div id="cf005f24" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if missing values in 'zip_code' and 'borough' always co-occur</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Count rows where both are missing</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>missing_cooccur <span class="op">=</span> df[[<span class="st">'zip_code'</span>, <span class="st">'borough'</span>]].isnull().<span class="bu">all</span>(axis<span class="op">=</span><span class="dv">1</span>).<span class="bu">sum</span>()</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Count total missing in 'zip_code' and 'borough', respectively</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>total_missing_zip_code <span class="op">=</span> df[<span class="st">'zip_code'</span>].isnull().<span class="bu">sum</span>()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>total_missing_borough <span class="op">=</span> df[<span class="st">'borough'</span>].isnull().<span class="bu">sum</span>()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># If missing in both columns always co-occur, the number of missing</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># co-occurrences should be equal to the total missing in either column</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>np.array([missing_cooccur, total_missing_zip_code, total_missing_borough])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>array([284, 284, 284])</code></pre>
</div>
</div>
<p>Are there cases where zip_code and borough are missing but the geo codes are not missing? If so, fill in <code>zip_code</code> and <code>borough</code> using the geo codes by reverse geocoding.</p>
<p>First make sure <code>geopy</code> is installed.</p>
<pre class="shell"><code>pip install geopy</code></pre>
<p>Now we use module <code>Nominatim</code> in package <code>geopy</code> to reverse geocode.</p>
<div id="953a6dc4" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> geopy.geocoders <span class="im">import</span> Nominatim</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize the geocoder; the `user_agent` is your identifier </span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># when using the service. Be mindful not to crash the server</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># by unlimited number of queries, especially invalid code.</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>geolocator <span class="op">=</span> Nominatim(user_agent<span class="op">=</span><span class="st">"jyGeopyTry"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We write a function to do the reverse geocoding given lattitude and longitude.</p>
<div id="da59c9cb" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to fill missing zip_code</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_zip_code(latitude, longitude):</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        location <span class="op">=</span> geolocator.reverse((latitude, longitude), timeout<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> location:</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>            address <span class="op">=</span> location.raw[<span class="st">'address'</span>]</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>            zip_code <span class="op">=</span> address.get(<span class="st">'postcode'</span>, <span class="va">None</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> zip_code</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Error: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss"> for coordinates </span><span class="sc">{</span>latitude<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>longitude<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">finally</span>:</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        time.sleep(<span class="dv">1</span>)  <span class="co"># Delay to avoid overwhelming the service</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s try it out:</p>
<div id="171f5c81" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>latitude <span class="op">=</span> <span class="fl">40.730610</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>longitude <span class="op">=</span> <span class="op">-</span><span class="fl">73.935242</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>get_zip_code(latitude, longitude)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>'11101'</code></pre>
</div>
</div>
<p>The function <code>get_zip_code</code> can then be applied to rows where zip code is missing but geocodes are not to fill the missing zip code.</p>
<p>Once zip code is known, figuring out <code>burough</code> is simple because valid zip codes from each borough are known.</p>
</section>
<section id="accessing-census-data" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="accessing-census-data"><span class="header-section-number">6.3</span> Accessing Census Data</h2>
<p>The U.S. Census Bureau provides extensive demographic, economic, and social data through multiple surveys, including the decennial Census, the American Community Survey (ACS), and the Economic Census. These datasets offer valuable insights into population trends, economic conditions, and community characteristics at multiple geographic levels.</p>
<p>There are multiple ways to access Census data. For example:</p>
<ul>
<li><strong>Census API</strong>: The <a href="https://www.census.gov/data/developers/data-sets.html">Census API</a> allows programmatic access to various datasets. It supports queries for different geographic levels and time periods.</li>
<li><strong>data.census.gov</strong>: The official <a href="https://data.census.gov/">web interface</a> for searching and downloading Census data.</li>
<li><strong>IPUMS USA</strong>: Provides harmonized microdata for longitudinal research. Available at <a href="https://usa.ipums.org/usa/">IPUMS USA</a>.</li>
<li><strong>NHGIS</strong>: Offers historical Census data with geographic information. Visit <a href="https://www.nhgis.org/">NHGIS</a>.</li>
</ul>
<p>In addition, Python tools simplify API access and data retrieval.</p>
<section id="python-tools-for-accessing-census-data" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="python-tools-for-accessing-census-data"><span class="header-section-number">6.3.1</span> Python Tools for Accessing Census Data</h3>
<p>Several Python libraries facilitate Census data retrieval:</p>
<ul>
<li><code>census</code>: A high-level interface to the Census API, supporting ACS and decennial Census queries. See <a href="https://pypi.org/project/census/"><code>census</code> on PyPI</a>.</li>
<li><code>censusdis</code>: Provides richer functionality: automatic discovery of variables, geographies, and datasets. Helpful if you don’t want to manually look up variable codes. See <a href="https://pypi.org/project/censusdis/"><code>censusdis</code> on PyPI</a>.</li>
<li><code>us</code>: Often used alongside census libraries to handle U.S. state and territory information (e.g., FIPS codes). See <a href="https://pypi.org/project/us/"><code>us</code> on PyPI</a>.</li>
</ul>
</section>
<section id="zip-code-level-for-nyc-crash-data" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="zip-code-level-for-nyc-crash-data"><span class="header-section-number">6.3.2</span> Zip-Code Level for NYC Crash Data</h3>
<p>Now that we have NYC crash data, we might want to analyze patterns at the zip-code level to understand whether certain demographic or economic factors correlate with traffic incidents. While the crash dataset provides details about individual accidents, such as location, time, and severity, it does not contain contextual information about the neighborhoods where these crashes occur.</p>
<p>To perform meaningful zip-code-level analysis, we need additional data sources that provide relevant demographic, economic, and geographic variables. For example, understanding whether high-income areas experience fewer accidents, or whether population density influences crash frequency, requires integrating Census data. Key variables such as population size, median household income, employment rate, and population density can provide valuable context for interpreting crash trends across different zip codes.</p>
<p>Since the Census Bureau provides detailed estimates for these variables at the zip-code level, we can use the Census API or other tools to retrieve relevant data and merge it with the NYC crash dataset. To access the Census API, you need an API key, which is free and easy to obtain. Visit the <a href="https://api.census.gov/data/key_signup.html">Census API Request page</a> and submit your email address to receive a key. Once you have the key, you must include it in your API requests to access Census data. The following demonstration assumes that you have registered, obtained your API key, and saved it in a file called <code>censusAPIkey.txt</code>.</p>
<div id="3bbf7eeb" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import modules</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> census <span class="im">import</span> Census</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> us <span class="im">import</span> states</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> io</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>api_key <span class="op">=</span> <span class="bu">open</span>(<span class="st">"censusAPIkey.txt"</span>).read().strip()</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>c <span class="op">=</span> Census(api_key)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Suppose that we want to get some basic info from ACS data of the year of 2024 for all the NYC zip codes. The variable names can be found in the <a href="https://www.census.gov/programs-surveys/acs/technical-documentation/table-shells.html">ACS variable documentation</a>.</p>
<div id="32711d0e" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ACS_YEAR <span class="op">=</span> <span class="dv">2024</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>ACS_DATASET <span class="op">=</span> <span class="st">"acs/acs5"</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Important ACS variables (including land area for density calculation)</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>ACS_VARIABLES <span class="op">=</span> {</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B01003_001E"</span>: <span class="st">"Total Population"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B19013_001E"</span>: <span class="st">"Median Household Income"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B02001_002E"</span>: <span class="st">"White Population"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B02001_003E"</span>: <span class="st">"Black Population"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B02001_005E"</span>: <span class="st">"Asian Population"</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B15003_022E"</span>: <span class="st">"Bachelor’s Degree Holders"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B15003_025E"</span>: <span class="st">"Graduate Degree Holders"</span>,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B23025_002E"</span>: <span class="st">"Labor Force"</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B23025_005E"</span>: <span class="st">"Unemployed"</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"B25077_001E"</span>: <span class="st">"Median Home Value"</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert set to list of strings</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>merged_zips <span class="op">=</span> <span class="bu">list</span>(<span class="bu">map</span>(<span class="bu">str</span>, merged_zips))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s set up the query to request the ACS data, and process the returned data.</p>
<div id="9f095846" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>acs_data <span class="op">=</span> c.acs5.get(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">list</span>(ACS_VARIABLES.keys()), </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    {<span class="st">'for'</span>: <span class="ss">f'zip code tabulation area:</span><span class="sc">{</span><span class="st">","</span><span class="sc">.</span>join(merged_zips)<span class="sc">}</span><span class="ss">'</span>}</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to DataFrame</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>df_acs <span class="op">=</span> pd.DataFrame(acs_data)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename columns</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>df_acs.rename(columns<span class="op">=</span>ACS_VARIABLES, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>df_acs.rename(columns<span class="op">=</span>{<span class="st">"zip code tabulation area"</span>: <span class="st">"ZIP Code"</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We could save the ACS data <code>df_acs</code> in feather format (see next Section).</p>
<div id="127c19cf" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_acs.to_feather(<span class="st">"data/acs2023.feather"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The population density could be an important factor for crash likelihood. To obtain the population densities, we need the areas of the zip codes. The shape files can be obtained from NYC Open Data.</p>
<div id="95b9839b" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> zipfile</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the NYC MODZCTA shapefile URL and extraction directory</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>shapefile_url <span class="op">=</span> <span class="st">"https://data.cityofnewyork.us/api/geospatial/pri4-ifjk?method=export&amp;format=Shapefile"</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>extract_dir <span class="op">=</span> <span class="st">"tmp/MODZCTA_Shapefile"</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the directory if it doesn't exist</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>os.makedirs(extract_dir, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Download and extract the shapefile</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Downloading MODZCTA shapefile..."</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(shapefile_url)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> zipfile.ZipFile(io.BytesIO(response.content), <span class="st">"r"</span>) <span class="im">as</span> z:</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    z.extractall(extract_dir)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shapefile extracted to: </span><span class="sc">{</span>extract_dir<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Downloading MODZCTA shapefile...
Shapefile extracted to: tmp/MODZCTA_Shapefile</code></pre>
</div>
</div>
<p>Now we process the shape file to calculate the areas of the polygons.</p>
<div id="cf73539b" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Automatically detect the correct .shp file</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>shapefile_path <span class="op">=</span> <span class="va">None</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> <span class="bu">file</span> <span class="kw">in</span> os.listdir(extract_dir):</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">file</span>.endswith(<span class="st">".shp"</span>):</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>        shapefile_path <span class="op">=</span> os.path.join(extract_dir, <span class="bu">file</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">break</span>  <span class="co"># Use the first .shp file found</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> shapefile_path:</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">FileNotFoundError</span>(<span class="st">"No .shp file found in extracted directory."</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Using shapefile: </span><span class="sc">{</span>shapefile_path<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Load the shapefile into GeoPandas</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>gdf <span class="op">=</span> gpd.read_file(shapefile_path)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: Convert to CRS with meters for accurate area calculation</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>gdf <span class="op">=</span> gdf.to_crs(epsg<span class="op">=</span><span class="dv">3857</span>)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Compute land area in square miles</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>gdf[<span class="st">'land_area_sq_miles'</span>] <span class="op">=</span> gdf[<span class="st">'geometry'</span>].area <span class="op">/</span> <span class="fl">2_589_988.11</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 square mile = 2,589,988.11 square meters</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gdf[[<span class="st">'modzcta'</span>, <span class="st">'land_area_sq_miles'</span>]].head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Using shapefile: tmp/MODZCTA_Shapefile/geo_export_02f6f870-06c5-4647-a884-845de8f40f63.shp
  modzcta  land_area_sq_miles
0   10001            1.153516
1   10002            1.534509
2   10003            1.008318
3   10026            0.581848
4   10004            0.256876</code></pre>
</div>
</div>
<p>Let’s export this data frame for future usage in feather format (see next Section).</p>
<div id="8fbebfc2" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>gdf[[<span class="st">'modzcta'</span>, <span class="st">'land_area_sq_miles'</span>]].to_feather(<span class="st">'data/nyc_zip_areas.feather'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we are ready to merge the two data frames.</p>
<div id="a55c572c" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge ACS data (`df_acs`) directly with MODZCTA land area (`gdf`)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>gdf <span class="op">=</span> gdf.merge(df_acs, left_on<span class="op">=</span><span class="st">'modzcta'</span>, right_on<span class="op">=</span><span class="st">'ZIP Code'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Population Density (people per square mile)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>gdf[<span class="st">'popdensity_per_sq_mile'</span>] <span class="op">=</span> (</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    gdf[<span class="st">'Total Population'</span>] <span class="op">/</span> gdf[<span class="st">'land_area_sq_miles'</span>]</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display first few rows</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gdf[[<span class="st">'modzcta'</span>, <span class="st">'Total Population'</span>, <span class="st">'land_area_sq_miles'</span>,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'popdensity_per_sq_mile'</span>]].head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  modzcta  Total Population  land_area_sq_miles  popdensity_per_sq_mile
0   10001           29079.0            1.153516            25209.019713
1   10002           75517.0            1.534509            49212.471465
2   10003           53825.0            1.008318            53380.992071
3   10026           37113.0            0.581848            63784.749994
4   10004            3875.0            0.256876            15085.082190</code></pre>
</div>
</div>
<p>Some visualization of population density.</p>
<div id="d9cdb831" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up figure and axis</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">12</span>))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the choropleth map</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>gdf.plot(column<span class="op">=</span><span class="st">'popdensity_per_sq_mile'</span>, </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>         cmap<span class="op">=</span><span class="st">'viridis'</span>,  <span class="co"># Use a visually appealing color map</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>         linewidth<span class="op">=</span><span class="fl">0.8</span>, </span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>         edgecolor<span class="op">=</span><span class="st">'black'</span>,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>         legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>         legend_kwds<span class="op">=</span>{<span class="st">'label'</span>: <span class="st">"Population Density (per sq mile)"</span>,</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>             <span class="st">'orientation'</span>: <span class="st">"horizontal"</span>},</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>         ax<span class="op">=</span>ax)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a title</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Population Density by ZCTA in NYC"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove axes</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([])</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>ax.set_yticks([])</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>ax.set_frame_on(<span class="va">False</span>)</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06-manipulation_files/figure-html/cell-22-output-1.png" width="763" height="874" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="cross-platform-data-format-arrow" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="cross-platform-data-format-arrow"><span class="header-section-number">6.4</span> Cross-platform Data Format <code>Arrow</code></h2>
<p>The CSV format (and related formats like TSV - tab-separated values) for data tables is ubiquitous, convenient, and can be read or written by many different data analysis environments, including spreadsheets. An advantage of the textual representation of the data in a CSV file is that the entire data table, or portions of it, can be previewed in a text editor. However, the textual representation can be ambiguous and inconsistent. The format of a particular column: Boolean, integer, floating-point, text, factor, etc. must be inferred from text representation, often at the expense of reading the entire file before these inferences can be made. Experienced data scientists are aware that a substantial part of an analysis or report generation is often the “data cleaning” involved in preparing the data for analysis. This can be an open-ended task — it required numerous trial-and-error iterations to create the list of different missing data representations we use for the sample CSV file and even now we are not sure we have them all.</p>
<p>To read and export data efficiently, leveraging the Apache <code>Arrow</code> library can significantly improve performance and storage efficiency, especially with large datasets. The IPC (Inter-Process Communication) file format in the context of Apache Arrow is a key component for efficiently sharing data between different processes, potentially written in different programming languages. Arrow’s IPC mechanism is designed around two main file formats:</p>
<ul>
<li>Stream Format: For sending an arbitrary length sequence of Arrow record batches (tables). The stream format is useful for real-time data exchange where the size of the data is not known upfront and can grow indefinitely.</li>
<li>File (or Feather) Format: Optimized for storage and memory-mapped access, allowing for fast random access to different sections of the data. This format is ideal for scenarios where the entire dataset is available upfront and can be stored in a file system for repeated reads and writes.</li>
</ul>
<p>Apache Arrow provides a columnar memory format for flat and hierarchical data, optimized for efficient data analytics. It can be used in Python through the <code>pyarrow</code> package. Here’s how you can use Arrow to read, manipulate, and export data, including a demonstration of storage savings.</p>
<p>First, ensure you have <code>pyarrow</code> installed on your computer (and preferrably, in your current virtual environment):</p>
<pre class="shell"><code>pip install pyarrow</code></pre>
<p>Feather is a fast, lightweight, and easy-to-use binary file format for storing data frames, optimized for speed and efficiency, particularly for IPC and data sharing between Python and R or Julia.</p>
<p>The following code processes the raw data in CSV format and write out in Arrow format.</p>
<div id="f017f7e5" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># File paths</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>csv_file <span class="op">=</span> <span class="st">'data/nyc_crashes_lbdwk_2025.csv'</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>feather_file <span class="op">=</span> <span class="st">'tmp/nyc_crashes_lbdwk_2025.feather'</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Move 'crash_datetime' to the first column</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[[<span class="st">'crash_datetime'</span>] <span class="op">+</span> df.drop(columns<span class="op">=</span>[<span class="st">'crash_datetime'</span>]).columns.tolist()]</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'zip_code'</span>] <span class="op">=</span> df[<span class="st">'zip_code'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.rstrip(<span class="st">'.0'</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.sort_values(by<span class="op">=</span><span class="st">'crash_datetime'</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>df.to_feather(feather_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s compare the file sizes of the feather format and the CSV format.</p>
<div id="61948a5e" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get file sizes in bytes</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>csv_size <span class="op">=</span> os.path.getsize(csv_file)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>feather_size <span class="op">=</span> os.path.getsize(feather_file)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert bytes to a more readable format (e.g., MB)</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>csv_size_mb <span class="op">=</span> csv_size <span class="op">/</span> (<span class="dv">1024</span> <span class="op">*</span> <span class="dv">1024</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>feather_size_mb <span class="op">=</span> feather_size <span class="op">/</span> (<span class="dv">1024</span> <span class="op">*</span> <span class="dv">1024</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the file sizes</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"CSV file size: </span><span class="sc">{</span>csv_size_mb<span class="sc">:.2f}</span><span class="ss"> MB"</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Feather file size: </span><span class="sc">{</span>feather_size_mb<span class="sc">:.2f}</span><span class="ss"> MB"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CSV file size: 0.27 MB
Feather file size: 0.13 MB</code></pre>
</div>
</div>
<p>Read the feather file back in:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>dff <span class="op">=</span> pd.read_feather(feather_file)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>dff.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<!-- This section is to be included as a tutorial for using pandas. -->
<!-- {{< include _pandas.qmd >}} -->
<!-- <\!-- This section is to be included as a tutorial for using SQL. -\-> -->
</section>
<section id="database-operation-with-sql" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="database-operation-with-sql"><span class="header-section-number">6.5</span> Database operation with SQL</h2>
<p>This section was prepared by Lewis Milun.</p>
<section id="introduction-1" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">6.5.1</span> Introduction</h3>
<p>Structured Query Language (SQL) is one of the standard languages that is used to work with large databases. It uses tables to store and display data, creating an organized and comprehensible interface that makes it far easier to track and view your data.</p>
<p>Some advantages of using SQL include its ability to handle large amounts of data while simultaneously simplifying the process of creating, updating, and retrieving any data you may want.</p>
<p>The biggest advantage of using SQL for the purposes of this class is that it can very easily connect with Python and R. This makes it so that we can have all of the benefits of working with SQL while still working in the Python environment we already have set up.</p>
</section>
<section id="setting-up-databases" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="setting-up-databases"><span class="header-section-number">6.5.2</span> Setting up Databases</h3>
<p>In this section, we will be working with two databases, one that’s built into a Python package (nycflights13) and one that we used for our midterm project (311 Service Requests)</p>
<section id="nycflights13" class="level4" data-number="6.5.2.1">
<h4 data-number="6.5.2.1" class="anchored" data-anchor-id="nycflights13"><span class="header-section-number">6.5.2.1</span> nycflights13</h4>
<p>This database uses the pandas package and includes flight data for all flights that left New York City airports in 2013. The database includes several tables including ones that detail each flight, airline, airport, and much more info regarding the flights. The data in this database is contained across several tables. Data stored like this would typically be irritating to deal with however it is proven simple when working with SQL.</p>
<p>To set up this database, we need to import the proper packages:</p>
<div id="67a2141e" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nycflights13 <span class="im">import</span> flights, airlines, airports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we imported “sqlite3” which is the package to import when working with SQL. We also imported “pandas” which also includes the nycflights13 database and from there imported the three tables we will be working with.</p>
<p>Now, we want to establish the connection between Python and our SQL database:</p>
<div id="85fce9cb" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>nycconn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">"nycflights13.db"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This snippet both creates the nycflights13.db database and establishes nycconn as our connection to this database.</p>
<p>Next step is to add the three tables we imported from nycflights13 to the database:</p>
<div id="156c3b00" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>flights.to_sql(<span class="st">"flights"</span>, nycconn, if_exists<span class="op">=</span><span class="st">"replace"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>airlines.to_sql(<span class="st">"airlines"</span>, nycconn, if_exists<span class="op">=</span><span class="st">"replace"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>airports.to_sql(<span class="st">"airports"</span>, nycconn, if_exists<span class="op">=</span><span class="st">"replace"</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What this does is converts the three pandas dataframes into tables in the SQL database. The if_exists argument handles what would happen if there is already a table in the database with the same name. The index argument is determining whether or not the first column of the dataframe should be handled as the index of the table in the dataframe.</p>
</section>
<section id="servicerequests-database" class="level4" data-number="6.5.2.2">
<h4 data-number="6.5.2.2" class="anchored" data-anchor-id="servicerequests-database"><span class="header-section-number">6.5.2.2</span> serviceRequests Database</h4>
<p>First, we need to import our serviceRequests data from the csv in the data folder:</p>
<div id="cbdf7bcf" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/serviceRequests06-09-2025_07-05-2025.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we need to repeat the process from nycflights13 but for our serviceRequests:</p>
<div id="24e96d7c" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>srconn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">"serviceRequests.db"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>df.to_sql(<span class="st">"requests"</span>, srconn, if_exists<span class="op">=</span><span class="st">"replace"</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we imported the dataframe we got from the csv file as the only table in the serviceRequests.db database.</p>
</section>
</section>
<section id="query-basics" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="query-basics"><span class="header-section-number">6.5.3</span> Query Basics</h3>
<p>Now we can move onto working with the data in our SQL databases. The most common use for SQL is writing a “query” which is a statement sent to the SQL database that returns a selection of rows and columns from the tables in a database.</p>
<p>We will be looking at the “flights” table in our nycflights13 database for this section.</p>
<section id="select-and-from" class="level4" data-number="6.5.3.1">
<h4 data-number="6.5.3.1" class="anchored" data-anchor-id="select-and-from"><span class="header-section-number">6.5.3.1</span> SELECT and FROM</h4>
<p>The following is the most basic possible query one can perform:</p>
<div id="84d601aa" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT *</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights;</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">day</th>
<th data-quarto-table-cell-role="th">dep_time</th>
<th data-quarto-table-cell-role="th">sched_dep_time</th>
<th data-quarto-table-cell-role="th">dep_delay</th>
<th data-quarto-table-cell-role="th">arr_time</th>
<th data-quarto-table-cell-role="th">sched_arr_time</th>
<th data-quarto-table-cell-role="th">arr_delay</th>
<th data-quarto-table-cell-role="th">carrier</th>
<th data-quarto-table-cell-role="th">flight</th>
<th data-quarto-table-cell-role="th">tailnum</th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
<th data-quarto-table-cell-role="th">air_time</th>
<th data-quarto-table-cell-role="th">distance</th>
<th data-quarto-table-cell-role="th">hour</th>
<th data-quarto-table-cell-role="th">minute</th>
<th data-quarto-table-cell-role="th">time_hour</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2013</td>
<td>1</td>
<td>1</td>
<td>517.0</td>
<td>515</td>
<td>2.0</td>
<td>830.0</td>
<td>819</td>
<td>11.0</td>
<td>UA</td>
<td>1545</td>
<td>N14228</td>
<td>EWR</td>
<td>IAH</td>
<td>227.0</td>
<td>1400</td>
<td>5</td>
<td>15</td>
<td>2013-01-01T10:00:00Z</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2013</td>
<td>1</td>
<td>1</td>
<td>533.0</td>
<td>529</td>
<td>4.0</td>
<td>850.0</td>
<td>830</td>
<td>20.0</td>
<td>UA</td>
<td>1714</td>
<td>N24211</td>
<td>LGA</td>
<td>IAH</td>
<td>227.0</td>
<td>1416</td>
<td>5</td>
<td>29</td>
<td>2013-01-01T10:00:00Z</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2013</td>
<td>1</td>
<td>1</td>
<td>542.0</td>
<td>540</td>
<td>2.0</td>
<td>923.0</td>
<td>850</td>
<td>33.0</td>
<td>AA</td>
<td>1141</td>
<td>N619AA</td>
<td>JFK</td>
<td>MIA</td>
<td>160.0</td>
<td>1089</td>
<td>5</td>
<td>40</td>
<td>2013-01-01T10:00:00Z</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2013</td>
<td>1</td>
<td>1</td>
<td>544.0</td>
<td>545</td>
<td>-1.0</td>
<td>1004.0</td>
<td>1022</td>
<td>-18.0</td>
<td>B6</td>
<td>725</td>
<td>N804JB</td>
<td>JFK</td>
<td>BQN</td>
<td>183.0</td>
<td>1576</td>
<td>5</td>
<td>45</td>
<td>2013-01-01T10:00:00Z</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2013</td>
<td>1</td>
<td>1</td>
<td>554.0</td>
<td>600</td>
<td>-6.0</td>
<td>812.0</td>
<td>837</td>
<td>-25.0</td>
<td>DL</td>
<td>461</td>
<td>N668DN</td>
<td>LGA</td>
<td>ATL</td>
<td>116.0</td>
<td>762</td>
<td>6</td>
<td>0</td>
<td>2013-01-01T11:00:00Z</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This snippet represents the basic form of writing SQL queries in Python. We create a variable ‘query’ that contains the statement we intend to pass into SQL. The last line then uses the nycconn connection we created earlier to pass our query into SQL and it returns the head() of the result we get back.</p>
<p>This query is the most basic query, as it returns the entire flights table. The SELECT line of the query is where you put the names of which columns you want from your table. You specify which table you want to work with on the FROM line. We put “*” in our SELECT line which returns all columns. All SQL queries must end with “;”, otherwise you’ll get an error.</p>
<p>Now let’s try to simplify what we’re seeing by only looking at the origins and destinations of the flights:</p>
<div id="4b8d3bbf" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT origin, dest</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights;</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>EWR</td>
<td>IAH</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>LGA</td>
<td>IAH</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>JFK</td>
<td>MIA</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>JFK</td>
<td>BQN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>LGA</td>
<td>ATL</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Here we replaced the “*” in our SELECT statement with “origin, dest” This told SQL to only return those two columns from the database.</p>
</section>
<section id="order-by" class="level4" data-number="6.5.3.2">
<h4 data-number="6.5.3.2" class="anchored" data-anchor-id="order-by"><span class="header-section-number">6.5.3.2</span> ORDER BY</h4>
<p>These columns are quite messy to look at so let’s try sorting them by origin:</p>
<div id="65471ca1" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT origin, dest</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin;</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>EWR</td>
<td>IAH</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>EWR</td>
<td>ORD</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>EWR</td>
<td>FLL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>EWR</td>
<td>SFO</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>EWR</td>
<td>LAS</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Here we added a new “ORDER BY” line. This line tells SQL what columns to sort the list by.</p>
<p>You can sort by multiple columns just by listing them with commas in between:</p>
<div id="33617230" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT origin, dest</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest;</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>EWR</td>
<td>ALB</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>EWR</td>
<td>ALB</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>EWR</td>
<td>ALB</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>EWR</td>
<td>ALB</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>EWR</td>
<td>ALB</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="select-distinct" class="level4" data-number="6.5.3.3">
<h4 data-number="6.5.3.3" class="anchored" data-anchor-id="select-distinct"><span class="header-section-number">6.5.3.3</span> SELECT DISTINCT</h4>
<p>Now that the list is properly sorted, we can see that there are multiple flights from each origin to destination combination. If we want to only see the unique columns, we can do this:</p>
<div id="6c77035d" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT origin, dest</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest;</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>EWR</td>
<td>ALB</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>EWR</td>
<td>ANC</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>EWR</td>
<td>ATL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>EWR</td>
<td>AUS</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>EWR</td>
<td>AVL</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Here we replaced our “SELECT” statement with a “SELECT DISTINCT” statement. This tells SQL to only return the unique columns from the query.</p>
</section>
</section>
<section id="conditionals" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="conditionals"><span class="header-section-number">6.5.4</span> Conditionals</h3>
<p>Usually you wouldn’t want to just return all rows or all unique rows from a table You instead will have conditions that determine which rows are relevant to your query</p>
<section id="where" class="level4" data-number="6.5.4.1">
<h4 data-number="6.5.4.1" class="anchored" data-anchor-id="where"><span class="header-section-number">6.5.4.1</span> WHERE</h4>
<p>The way you can add conditionals to your query is by adding a “WHERE” line. Let’s take the same list from the last section and filter it so that only the flights that departed from LGA are returned:</p>
<div id="d4d98b7c" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT origin, dest</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE origin = 'LGA'</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest;</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>LGA</td>
<td>ATL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>LGA</td>
<td>AVL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>LGA</td>
<td>BGR</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>LGA</td>
<td>BHM</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>LGA</td>
<td>BNA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>You add conditionals in the “WHERE” line by using the following comparators:</p>
<ul>
<li>‘=’</li>
<li>‘&lt;’</li>
<li>‘&gt;’</li>
<li>‘&lt;=’</li>
<li>‘&gt;=’</li>
<li>‘!=’</li>
</ul>
<p>Be careful of the type of the data in a particular column!</p>
</section>
<section id="and-or-and-not" class="level4" data-number="6.5.4.2">
<h4 data-number="6.5.4.2" class="anchored" data-anchor-id="and-or-and-not"><span class="header-section-number">6.5.4.2</span> AND, OR, and NOT</h4>
<p>You can add multiple conditionals by using AND, OR, and parentheses</p>
<div id="aca729cf" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT origin, dest</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE origin = 'LGA' AND dest = 'ATL'</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest;</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>LGA</td>
<td>ATL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>LGA</td>
<td>ATL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>LGA</td>
<td>ATL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>LGA</td>
<td>ATL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>LGA</td>
<td>ATL</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This uses AND to return all flights that departed from LGA and arrived in ATL</p>
<p>We can also use OR to return all flights that either departed from LGA or arrived in ATL:</p>
<div id="0a7b4835" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT origin, dest</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE origin = 'LGA' OR dest = 'ATL'</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest;</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>EWR</td>
<td>ATL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>JFK</td>
<td>ATL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>LGA</td>
<td>ATL</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>LGA</td>
<td>AVL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>LGA</td>
<td>BGR</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>When you want to get more complicated with your conditionals, parenthesis can be used to ensure SQL is correctly mixing the AND and OR statements.</p>
<p>Use NOT to return the opposite of a statement:</p>
<div id="3cdae074" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT origin, dest</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE NOT (origin = 'LGA' OR dest = 'ATL')</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest;</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>EWR</td>
<td>ALB</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>EWR</td>
<td>ANC</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>EWR</td>
<td>AUS</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>EWR</td>
<td>AVL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>EWR</td>
<td>BDL</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="count" class="level4" data-number="6.5.4.3">
<h4 data-number="6.5.4.3" class="anchored" data-anchor-id="count"><span class="header-section-number">6.5.4.3</span> COUNT</h4>
<p>An easy way in SQL to see the total number of rows that fit the conditions you’ve specified:</p>
<div id="8a944d5a" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT COUNT(DISTINCT dest)</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE NOT (origin = 'LGA' OR dest = 'ATL');</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">COUNT(DISTINCT dest)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>97</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This returns the number of distinct destinations that fit the specified criteria</p>
</section>
<section id="limit" class="level4" data-number="6.5.4.4">
<h4 data-number="6.5.4.4" class="anchored" data-anchor-id="limit"><span class="header-section-number">6.5.4.4</span> LIMIT</h4>
<p>If you don’t want to use .head() to only display the first few rows, this can be done in SQL using a LIMIT statement:</p>
<div id="87cd0d14" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT carrier, origin, dest</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE carrier = 'UA'</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="st">LIMIT 5;</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">carrier</th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>UA</td>
<td>EWR</td>
<td>ANC</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>UA</td>
<td>EWR</td>
<td>ATL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>UA</td>
<td>EWR</td>
<td>AUS</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>UA</td>
<td>EWR</td>
<td>BDL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>UA</td>
<td>EWR</td>
<td>BOS</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This query added the “carrier” column that displays the airline that held the flight. We specified that we want all flights from the “UA” airline and limited the result to 5 rows.</p>
<p>An interesting thing you can do with conditionals in SQL is to filter by values in a column that you are not displaying:</p>
<div id="9fc1fc15" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT origin, dest</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="st">WHERE carrier = 'UA'</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY origin, dest</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="st">LIMIT 5;</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>EWR</td>
<td>ANC</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>EWR</td>
<td>ATL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>EWR</td>
<td>AUS</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>EWR</td>
<td>BDL</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>EWR</td>
<td>BOS</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Here we still filter by flights from the “UA” airline but we don’t display the column as that would be very redundant.</p>
</section>
</section>
<section id="joins" class="level3" data-number="6.5.5">
<h3 data-number="6.5.5" class="anchored" data-anchor-id="joins"><span class="header-section-number">6.5.5</span> Joins</h3>
<p>The last query that we did was useful, however it isn’t realistic to expect users to memorize the two-digit codes for all airlines. Thankfully, there is the airlines table in our nycflights13.db database. Let’s take a look at it:</p>
<div id="49d1f1b4" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT *</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM airlines;</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="39">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">carrier</th>
<th data-quarto-table-cell-role="th">name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>9E</td>
<td>Endeavor Air Inc.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>AA</td>
<td>American Airlines Inc.</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>AS</td>
<td>Alaska Airlines Inc.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>B6</td>
<td>JetBlue Airways</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>DL</td>
<td>Delta Air Lines Inc.</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This table is much simpler than the “flights” table as it only has two columns.</p>
<section id="inner-join" class="level4" data-number="6.5.5.1">
<h4 data-number="6.5.5.1" class="anchored" data-anchor-id="inner-join"><span class="header-section-number">6.5.5.1</span> INNER JOIN</h4>
<p>Logically, we wouldn’t want our outputted table to display the two-digit code that represents each airline but instead we’d want to see the name of the airline. Thankfully, SQL has a way to join the data from the two tables together:</p>
<div id="ad38a858" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT a.name AS airline_name, f.origin, f.dest</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights AS f</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN airlines AS a</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="st">ON f.carrier = a.carrier;</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">airline_name</th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>United Air Lines Inc.</td>
<td>EWR</td>
<td>IAH</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>United Air Lines Inc.</td>
<td>LGA</td>
<td>IAH</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>American Airlines Inc.</td>
<td>JFK</td>
<td>MIA</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>JetBlue Airways</td>
<td>JFK</td>
<td>BQN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Delta Air Lines Inc.</td>
<td>LGA</td>
<td>ATL</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This is a much more complicated query that returns a table of the distinct airline, origin, and destination in the flights database. We introduced three new statements in this query:</p>
<p>AS is similar to how “as” is used when importing packages in Python. It gives us an opportunity to use a shorthand instead of needing to type out the full table names every time we mention a column. It can also be used in our SELECT line to name columns in our resultant table</p>
<p>INNER JOIN connects a new table to our query (in this case, the new table is airlines).</p>
<p>ON lets SQL know what column in each table it should use to connect the tables. Here we told SQL that in every row, when it reaches the carrier column in flights, it should use that as its reference for what row in airlines to use for values in this row. For example, in the first row, SQL saw that the carrier name in flights was “UA”. SQL then looked in the carrier column in airlines and found the row in which “UA” was the value in that table’s carrier column. So when SQL was calculating the value for airline_name in the first row, it knew which column to search in airline to find “United Air Lines Inc.”</p>
<p>JOIN statements are key when using SQL to display data. This is what allows SQL databases to be in such nice and concise structures.</p>
<p>Now let’s also add in the values from the “airports” table so that we get the full names of the airports instead of their three-digit codes:</p>
<div id="1b46499c" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT a.name AS airline_name,</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="st">       orig.name AS origin_name,</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="st">       dest.name AS dest_name</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights AS f</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN airlines AS a</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.carrier = a.carrier</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN airports AS orig</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.origin = orig.faa</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN airports AS dest</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.dest = dest.faa;</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">airline_name</th>
<th data-quarto-table-cell-role="th">origin_name</th>
<th data-quarto-table-cell-role="th">dest_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>United Air Lines Inc.</td>
<td>Newark Liberty Intl</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>United Air Lines Inc.</td>
<td>La Guardia</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>American Airlines Inc.</td>
<td>John F Kennedy Intl</td>
<td>Miami Intl</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Delta Air Lines Inc.</td>
<td>La Guardia</td>
<td>Hartsfield Jackson Atlanta Intl</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>United Air Lines Inc.</td>
<td>Newark Liberty Intl</td>
<td>Chicago Ohare Intl</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Here we use three different INNER JOIN statements to connect the three tables properly. The reason we use two JOIN statements to connect the same “airports” table is to have SQL be able to look separately for the origin and destination airport names. This query also utilizes indenting to make the query far more readable.</p>
</section>
<section id="the-difference-between-the-three-joins" class="level4" data-number="6.5.5.2">
<h4 data-number="6.5.5.2" class="anchored" data-anchor-id="the-difference-between-the-three-joins"><span class="header-section-number">6.5.5.2</span> The difference between the three JOINs</h4>
<p>SQL has three different versions of JOIN statements: + INNER JOIN + LEFT JOIN + RIGHT JOIN</p>
<p>This allows the user to determine what rows get included as a result of joining two tables. Let’s take a look at the differences:</p>
<div id="cfc0c093" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT f.flight,</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="st">       a.name AS airline_name,</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="st">       orig.name AS origin_name,</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="st">       dest.name AS dest_name</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights AS f</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN airlines AS a</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.carrier = a.carrier</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN airports AS orig</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.origin = orig.faa</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="st">INNER JOIN airports AS dest</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.dest = dest.faa;</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">flight</th>
<th data-quarto-table-cell-role="th">airline_name</th>
<th data-quarto-table-cell-role="th">origin_name</th>
<th data-quarto-table-cell-role="th">dest_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1545</td>
<td>United Air Lines Inc.</td>
<td>Newark Liberty Intl</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1714</td>
<td>United Air Lines Inc.</td>
<td>La Guardia</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1141</td>
<td>American Airlines Inc.</td>
<td>John F Kennedy Intl</td>
<td>Miami Intl</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>461</td>
<td>Delta Air Lines Inc.</td>
<td>La Guardia</td>
<td>Hartsfield Jackson Atlanta Intl</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1696</td>
<td>United Air Lines Inc.</td>
<td>Newark Liberty Intl</td>
<td>Chicago Ohare Intl</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>INNER JOIN is the most common. This is because the result will only include rows in which the values in question are included in both tables. For example, if there was a row in flights that included an airline code that was not present in airlines, then SQL will not include that row in the result.</p>
<div id="b848b349" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT f.flight,</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="st">    a.name AS airline_name,</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="st">    orig.name AS origin_name,</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="st">    dest.name AS dest_name</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights AS f</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="st">LEFT JOIN airlines AS a</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.carrier = a.carrier</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a><span class="st">LEFT JOIN airports AS orig</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.origin = orig.faa</span></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="st">LEFT JOIN airports AS dest</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.dest = dest.faa;</span></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">flight</th>
<th data-quarto-table-cell-role="th">airline_name</th>
<th data-quarto-table-cell-role="th">origin_name</th>
<th data-quarto-table-cell-role="th">dest_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1545</td>
<td>United Air Lines Inc.</td>
<td>Newark Liberty Intl</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1714</td>
<td>United Air Lines Inc.</td>
<td>La Guardia</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1141</td>
<td>American Airlines Inc.</td>
<td>John F Kennedy Intl</td>
<td>Miami Intl</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>725</td>
<td>JetBlue Airways</td>
<td>John F Kennedy Intl</td>
<td>None</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>461</td>
<td>Delta Air Lines Inc.</td>
<td>La Guardia</td>
<td>Hartsfield Jackson Atlanta Intl</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>LEFT JOIN will return all rows that are in flights regardless of if SQL was able to find matching rows on the other tables. This is perfectly represented in the fourth row of the output. On flights, the destination for flight 725 is “BQN” which is not an airport on the airports table. If you look back to the result of the INNER JOIN, this row was removed from the result however it is present here because we used flights as our only reference for rows and therefore the row is included but the destination name is left as “None”</p>
<div id="7a2fefd5" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT f.flight,</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="st">    f.origin,</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="st">    dest.name AS dest_name</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="st">FROM flights AS f</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="st">RIGHT JOIN airports AS dest</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="st">    ON f.dest = dest.faa;</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, nycconn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">flight</th>
<th data-quarto-table-cell-role="th">origin</th>
<th data-quarto-table-cell-role="th">dest_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1545.0</td>
<td>EWR</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1714.0</td>
<td>LGA</td>
<td>George Bush Intercontinental</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1141.0</td>
<td>JFK</td>
<td>Miami Intl</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>461.0</td>
<td>LGA</td>
<td>Hartsfield Jackson Atlanta Intl</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1696.0</td>
<td>EWR</td>
<td>Chicago Ohare Intl</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13275</td>
<td>NaN</td>
<td>None</td>
<td>Boston Back Bay Station</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13276</td>
<td>NaN</td>
<td>None</td>
<td>Black Rock</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13277</td>
<td>NaN</td>
<td>None</td>
<td>New Haven Rail Station</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13278</td>
<td>NaN</td>
<td>None</td>
<td>Wilmington Amtrak Station</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13279</td>
<td>NaN</td>
<td>None</td>
<td>Washington Union Station</td>
</tr>
</tbody>
</table>

<p>13280 rows × 3 columns</p>
</div>
</div>
</div>
<p>RIGHT JOIN is basically the opposite of LEFT JOIN. Instead of using flights as its basis for what rows to include, RIGHT JOIN uses the joined tables instead. As you can see, the fourth row is being skipped again because the airports table is being used as reference instead. Also, the table ends with rows for all destinations from the airports table. SQL includes them because it is looking for all rows that include destinations from the airports table. This includes all rows from the airports table itself.</p>
</section>
</section>
<section id="creating-tables" class="level3" data-number="6.5.6">
<h3 data-number="6.5.6" class="anchored" data-anchor-id="creating-tables"><span class="header-section-number">6.5.6</span> Creating Tables</h3>
<p>Let’s take a look at our serviceRequests.db’s requests table:</p>
<div id="964c69a3" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT *</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM requests;</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, srconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Unique Key</th>
<th data-quarto-table-cell-role="th">Created Date</th>
<th data-quarto-table-cell-role="th">Closed Date</th>
<th data-quarto-table-cell-role="th">Agency</th>
<th data-quarto-table-cell-role="th">Agency Name</th>
<th data-quarto-table-cell-role="th">Complaint Type</th>
<th data-quarto-table-cell-role="th">Descriptor</th>
<th data-quarto-table-cell-role="th">Location Type</th>
<th data-quarto-table-cell-role="th">Incident Zip</th>
<th data-quarto-table-cell-role="th">Incident Address</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Vehicle Type</th>
<th data-quarto-table-cell-role="th">Taxi Company Borough</th>
<th data-quarto-table-cell-role="th">Taxi Pick Up Location</th>
<th data-quarto-table-cell-role="th">Bridge Highway Name</th>
<th data-quarto-table-cell-role="th">Bridge Highway Direction</th>
<th data-quarto-table-cell-role="th">Road Ramp</th>
<th data-quarto-table-cell-role="th">Bridge Highway Segment</th>
<th data-quarto-table-cell-role="th">Latitude</th>
<th data-quarto-table-cell-role="th">Longitude</th>
<th data-quarto-table-cell-role="th">Location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>65477840</td>
<td>07/05/2025 11:59:51 AM</td>
<td>None</td>
<td>EDC</td>
<td>Economic Development Corporation</td>
<td>Noise - Helicopter</td>
<td>Other</td>
<td>Above Address</td>
<td>11414.0</td>
<td>88-12 151 AVENUE</td>
<td>...</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>40.668478</td>
<td>-73.846874</td>
<td>(40.6684777987759, -73.84687384879807)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>65473303</td>
<td>07/05/2025 11:59:38 AM</td>
<td>07/05/2025 12:53:29 PM</td>
<td>NYPD</td>
<td>New York City Police Department</td>
<td>Blocked Driveway</td>
<td>Partial Access</td>
<td>Street/Sidewalk</td>
<td>11207.0</td>
<td>737 CHAUNCEY STREET</td>
<td>...</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>40.685343</td>
<td>-73.907410</td>
<td>(40.685343220141434, -73.90741025722555)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>65479182</td>
<td>07/05/2025 11:59:30 AM</td>
<td>07/05/2025 07:24:47 PM</td>
<td>DHS</td>
<td>Department of Homeless Services</td>
<td>Homeless Person Assistance</td>
<td>Chronic</td>
<td>Store/Commercial</td>
<td>10014.0</td>
<td>11 LITTLE WEST 12 STREET</td>
<td>...</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>40.739795</td>
<td>-74.006708</td>
<td>(40.739795176046364, -74.00670839867178)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>65472680</td>
<td>07/05/2025 11:59:27 AM</td>
<td>07/05/2025 02:28:38 PM</td>
<td>NYPD</td>
<td>New York City Police Department</td>
<td>Abandoned Vehicle</td>
<td>With License Plate</td>
<td>Street/Sidewalk</td>
<td>10039.0</td>
<td>2743 FREDERICK DOUGLASS BOULEVARD</td>
<td>...</td>
<td>Car</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>40.823646</td>
<td>-73.941340</td>
<td>(40.82364581471349, -73.94134045287531)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>65479165</td>
<td>07/05/2025 11:59:20 AM</td>
<td>07/06/2025 01:13:50 AM</td>
<td>NYPD</td>
<td>New York City Police Department</td>
<td>Encampment</td>
<td>None</td>
<td>Residential Building/House</td>
<td>10456.0</td>
<td>1398 GRAND CONCOURSE</td>
<td>...</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>None</td>
<td>40.838557</td>
<td>-73.913883</td>
<td>(40.83855707927812, -73.91388286014495)</td>
</tr>
</tbody>
</table>

<p>5 rows × 41 columns</p>
</div>
</div>
</div>
<p>This table is incredibly complicated and redundant through repeated information such as each row having both “Agency” and “Agency Name”. This redundancy clutters the table, making it difficult to read. It would be much better if the database wasn’t just one table and instead was formatted like the nycflights13.db</p>
<p>Take note that we have begun using our other connection (srconn instead of nycconn) because we are working with our other database.</p>
<p>Thankfully, SQL makes it very simple to create new tables from the results of a query. Looking back at the redundancy with agencies, we can create the following query to see all the agency codes and their corresponding names:</p>
<div id="46e7ce45" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT Agency, "Agency Name"</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM requests</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY Agency;</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, srconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="46">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Agency</th>
<th data-quarto-table-cell-role="th">Agency Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>DCWP</td>
<td>Department of Consumer and Worker Protection</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>DEP</td>
<td>Department of Environmental Protection</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>DHS</td>
<td>Department of Homeless Services</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>DOB</td>
<td>Department of Buildings</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>DOE</td>
<td>Department of Education</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Something to note here is how one can handle a column name that includes a space or a comma. If you put the name of the column in quotes, then SQL will handle everything inside the quotes as the name of the column.</p>
<p>Now that we have created this query, we can make the result into its own table in the database:</p>
<div id="a963c0b8" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="st">CREATE TABLE IF NOT EXISTS agencies AS</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT DISTINCT Agency, "Agency Name"</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="st">FROM requests</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="st">ORDER BY Agency;</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>srconn.execute(query)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>srconn.commit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are a few key parts to this query:</p>
<p>Firstly, we have the first line which tells SQL to create a table named agencies and the AS works here to tell SQL to make the table be the result of the query that follows the first line.</p>
<p>Second, there is the statement “IF NOT EXISTS”. This is incredibly useful to include in the query as it ensures that you do not override any tables that you have previously made.</p>
<p>Lastly, we use different commands outside of creating the query variable. Instead of pd.read_sql_query(query, srconn), we have our connection to SQL execute the query we created, then commit the changes to the database.</p>
<p>Now that we have added the table to our database, we can query it:</p>
<div id="7ba28dbc" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>query <span class="op">=</span> <span class="st">"""</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="st">SELECT *</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="st">FROM agencies;</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>pd.read_sql_query(query, srconn).head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Agency</th>
<th data-quarto-table-cell-role="th">Agency Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>DCWP</td>
<td>Department of Consumer and Worker Protection</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>DEP</td>
<td>Department of Environmental Protection</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>DHS</td>
<td>Department of Homeless Services</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>DOB</td>
<td>Department of Buildings</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>DOE</td>
<td>Department of Education</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This process can be repeated to clean up messy tables and messy databases.</p>
</section>
<section id="statement-order" class="level3" data-number="6.5.7">
<h3 data-number="6.5.7" class="anchored" data-anchor-id="statement-order"><span class="header-section-number">6.5.7</span> Statement Order</h3>
<p>Statements in a SQL query must go in a certain order, otherwise the query will return an error. The order is as follows:</p>
<ol type="1">
<li>SELECT</li>
<li>FROM</li>
<li>JOIN</li>
<li>WHERE</li>
<li>GROUP BY</li>
<li>HAVING</li>
<li>ORDER BY</li>
<li>LIMIT/OFFSET</li>
</ol>
</section>
<section id="conclusion" class="level3" data-number="6.5.8">
<h3 data-number="6.5.8" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6.5.8</span> Conclusion</h3>
<p>SQL makes working with large datasets much easier by organizing databases and simplifying the process of displaying data. Using either the queries shown here as well as much more complicated queries, one can turn complex tables into databases that don’t unnecessarily repeat data, and that consist of easily read tables.</p>
</section>
<section id="further-readings" class="level3" data-number="6.5.9">
<h3 data-number="6.5.9" class="anchored" data-anchor-id="further-readings"><span class="header-section-number">6.5.9</span> Further Readings</h3>
<ol type="1">
<li><a href="https://www.w3schools.com/sql/default.asp">W3 Schools SQL Tutorial</a></li>
<li>[SQLite Tutorial (installing SQLite not necessary)] (https://www.sqlitetutorial.net/)</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-visualization.html" class="pagination-link" aria-label="Data Visualization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-exploration.html" class="pagination-link" aria-label="Data Exploration">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data Exploration</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>